import fs from 'fs';
import path from 'path';
import { groth16 } from 'snarkjs';

/**
 * Supported circuit types for proof verification.
 */
export type CircuitType = 'non_inclusion' | 'update';

/**
 * Result of proof verification.
 */
export interface ProofVerificationResult {
  valid: boolean;
  message: string;
}

/**
 * Verifies a Groth16 proof against the correct verification key for the given circuit type.
 * @param type - The circuit type ('non_inclusion' or 'update').
 * @param proof - The proof object (as generated by snarkjs proof scripts).
 * @param publicSignals - The public signals array.
 * @returns ProofVerificationResult with validity and status message.
 */
export async function verifyProof(
  type: CircuitType,
  proof: any,
  publicSignals: any
): Promise<ProofVerificationResult> {
  try {
    const vkeyPath = getVerificationKeyPath(type);
    if (!fs.existsSync(vkeyPath)) {
      return { valid: false, message: `Verification key not found: ${vkeyPath}` };
    }
    const vkey = JSON.parse(fs.readFileSync(vkeyPath, 'utf-8'));
    const res = await groth16.verify(vkey, publicSignals, proof);
    if (res === true) {
      return { valid: true, message: 'Proof is valid.' };
    } else {
      return { valid: false, message: 'Proof is invalid.' };
    }
  } catch (err: any) {
    return { valid: false, message: `Verification error: ${err.message}` };
  }
}

/**
 * Returns the path to the verification key for the given circuit type.
 * @param type - The circuit type.
 */
function getVerificationKeyPath(type: CircuitType): string {
  switch (type) {
    case 'non_inclusion':
      return path.join(__dirname, '../build/merkle_non_inclusion/verification_key.json');
    case 'update':
      return path.join(__dirname, '../build/merkle_update/verification_key.json');
    default:
      throw new Error(`Unsupported circuit type: ${type}`);
  }
}
