name: Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ,"dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: gateway-contract

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        targets: wasm32-unknown-unknown

    - name: Check formatting
      run: cargo fmt --all --check

    - name: Run Clippy lints
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings

    - name: Cargo check
      run: |
        source $HOME/.cargo/env
        cargo check --verbose

    - name: Build contracts for wasm32v1-none
      run: |
        source $HOME/.cargo/env
        cargo build --target wasm32v1-none --release --verbose
